from centos
MAINTAINER meisanggou

RUN rm -rf /etc/yum.repos.d/*.repo && \
    curl -o /etc/yum.repos.d/CentOS-Base.repo https://repo.huaweicloud.com/repository/conf/CentOS-8-reg.repo && \
    dnf install -y python38 pandoc texlive texlive-collection-xetex && \
    dnf clean all && rm -rf /var/char/dnf

ADD Dockerfile /root/centos_py_pandoc
