services:
  wildzh:
    container_name: wildzh
    environment:
     - ES_HOST=127.0.0.1
     - ES_PORT=9200
     - ZH_UPLOAD_FOLDER=/opt/upload
     - EXEC_USER_ID=$EXEC_USER_ID
     - LOG_FILE=true
    network_mode: host
    image: meisanggou/wildzh
    restart: always
    volumes:
    - ../:/opt/wildzh
    - $ZH_UPLOAD_FOLDER:/opt/upload
  wildzh-es2:
    container_name: wildzh-es2
    environment:
      - discovery.type=single-node
    network_mode: host
    image: meisanggou/elasticsearch-ik:7.7.1
    restart: always
    volumes:
      - /mnt/JINGD/data/es:/usr/share/elasticsearch/data
version: '2.4'

